title: 96boards.ai

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://96boards.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

theme: jumbo-jekyll-theme

plugins:
  - jekyll-data

# Jekyll Collections configuration - Projects, Products and Documentation.
# These are the 96boards.ai collections
collections:
    product:
        output: true
        permalink: /:collection/:path/
        layout: ai-product
    documentation:
        output: true
        permalink: /:collection/:path/
        layout: ai-docs