title: 96Boards.ai
description: Providing Developer Platforms for AI Solutions.
baseurl: ""
url: "https://96Boards.ai"
twitter_username: jekyllrb
github_username:  jekyll
theme: jumbo-jekyll-theme
plugins:
  - jekyll-data
  - jekyll-readme-index
# Files that should be excluded from the Jekyll build.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - .sass-cache
  - _site
  - help
  - node_modules
  - build.sh
  - README.md
collections:
    products:
        output: true
        permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
readme_index:
  enabled:          true
  remove_originals: true